version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"

  sensor:
    build: ./sensors
    depends_on:
      - backend
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpassword
      POSTGRES_DB: iotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
